server:
  port: 8080

logging:
  level:
    root: INFO
    com.github.bluealis: DEBUG

spring:
  application:
    name: spring-boot-testbbl
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/testbbl_db
    driver-class-name: org.postgresql.Driver
    username: dev
    password: "dev"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
